/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iUniswapSol from "./IUniswap.sol";
export type { iUniswapSol };
import type * as votingSol from "./voting.sol";
export type { votingSol };
export type { IVoting } from "./IVoting";
export type { Lock } from "./Lock";
