/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as votingSol from "./voting.sol";
export { IVoting__factory } from "./IVoting__factory";
export { Lock__factory } from "./Lock__factory";
