/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as votingSol from "./voting.sol";
export type { votingSol };
export type { IVoting } from "./IVoting";
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { IVoting__factory } from "./factories/IVoting__factory";
export { Lock__factory } from "./factories/Lock__factory";
export type { Voting } from "./voting.sol/Voting";
export { Voting__factory } from "./factories/voting.sol/Voting__factory";
